spring:
  application:
    name: vote
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      uri: ${spring.cloud.config.uri:http://localhost:8888}
      username: ${CONFIG_SERVER_USR}
      password: ${CONFIG_SERVER_PWD}

server:
  port: 6369
  logging:
    level:
      org.springframework: DEBUG

---
spring:
  profiles:
    active: docker

  cloud:
    config:
      uri: http://localhost:9789
      enabled: false
